[tool.poetry]
name = "DashboardLeaf"
version = "1.20.0"
description = "Flask server for displaying multiple dashboards with custom tiles that refresh periodically."
authors = ["TheCodeLabsDevs"]

[[tool.poetry.source]]
name = "TheCodeLabs"
url = "https://pypi.thecodelabs.de"
secondary = true

[tool.poetry.dependencies]
python = "^3.9"
thecodelabs-baseutils = "*"
thecodelabs-flaskutils = "*"
flask = "2.3.2"
apscheduler = "3.10.1"
gevent = "23.7.0"
flask-socketio= "5.3.5"
Babel = "2.12.1"

# services
icalendar = "5.0.7"

# tiles
timeago = "1.0.16"

[tool.poetry.dev-dependencies]
pytest= "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
