[tool.poetry]
name = "DashboardLeaf"
version = "1.29.0"
description = "Flask server for displaying multiple dashboards with custom tiles that refresh periodically."
authors = ["TheCodeLabsDevs"]
packages = [{include = "dashboard_leaf"}]

[[tool.poetry.source]]
name = "TheCodeLabs"
url = "https://pypi.thecodelabs.de"
priority = "explicit"

[tool.poetry.dependencies]
python = "^3.9"
thecodelabs-baseutils = {version = "*", source = "TheCodeLabs" }
thecodelabs-flaskutils = {version = "*", source = "TheCodeLabs" }
flask = "3.0.3"
apscheduler = "3.10.4"
gevent = "24.2.1"
flask-socketio = "5.3.6"
Babel = "2.15.0"

# services
icalendar = "5.0.13"

# tiles
timeago = "1.0.16"

[tool.poetry.dev-dependencies]
pytest= "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
